### ISSUE TITLE
Crashes on startup on Linux with Intel graphics

### ISSUE THREAD

**Issue by jonnor** [jaamsim/jaamsim#3]
When starting JaamSim, with the current .jar on Arch Linux x86_64 with Intel graphics the different windows start popping up, but then the program crashes and outputs on console is:
`intel_do_flush_locked failed: No such file or directory`

This happens both if I use `java -jar ./JaamSim2017-01.jar ./Server_and_Queue_Example.cfg` or
`java -jar ./JaamSim2017-01.jar`.

```
[jon@jon-portable Downloads]$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by hharrison** [comment]
I'm guessing Sandybridge graphics? Most likely it is this known bug in the
Intel driver (open since 2013), we have no fix for it, sorry. You can

https://bugs.freedesktop.org/show_bug.cgi?id=41736

You can force software rendering which will be slower, but will at least
allow you to use jaamsim:

export LIBGL_ALWAYS_SOFTWARE=1java -jar ./JaamSim2017-01.jar


Please let me know if that workaround gets you any further.

Harvey
